# Generated by Django 4.2.6 on 2023-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('rating', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
