# Generated by Django 4.2.6 on 2023-10-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_reviews', '0004_alter_productreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
