# Generated by Django 4.2.6 on 2023-10-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('product_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(default='')),
                ('price', models.PositiveIntegerField()),
                ('product_kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_categories.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
